settings:
  title: 'Site Status'
  url: 'https://status.vmail.dev' # used for Slack messages
  logo: vmail.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: vmail-dev # unique identifier
    name: vmail.dev
    description: 'Virtual temporary Email. Privacy friendly, Valid for 1 day, AD friendly, 100% Run on Cloudflare.' # default=empty
    url: 'https://vmail.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: search-vmail-dev # unique identifier
    name: search.vmail.dev
    description: 'Google search mirror' # default=empty
    url: 'https://search.vmail.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: iconce-com # unique identifier
    name: iconce.com
    description: 'Svg icon generator.' # default=empty
    url: 'https://iconce.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: inke-app # unique identifier
    name: Inke.app
    description: 'AI note app.' # default=empty
    url: 'https://inke.app' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: dev-yesmore-cc # unique identifier
    name: dev.yesmore.cc
    description: 'My blog.' # default=empty
    url: 'https://dev.yesmore.cc' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

